# Exclude some of GitLab files
AllCops:
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'hooks/**/*'
    - 'support/**/*'
    - 'Guardfile'

Layout/DotPosition:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
